main: com.swiftlicious.hellblock.HellblockPlugin
name: Hellblock
version: '${version}'
api-version: 1.20.5
description: Skyblock in the nether!
website: https://github.com/Swiftlicious01?tab=repositories
authors: [ Swiftlicious ]
folia-supported: true
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
    WorldEdit:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    AdvancedEnchantments:
      load: BEFORE
      required: false
    Jobs:
      load: BEFORE
      required: false
    Multiverse-Core:
      load: BEFORE
      required: false

permissions:
  hellblock.user:
    description: Main permission
    default: not op
  hellblock.coop:
    description: Coop permission
    default: not op
  hellblock.admin:
    description: Admin permission
    default: op
  hellblock.updates:
    description: Get latest update messages!
    default: op