main: com.swiftlicious.hellblock.HellblockPlugin
name: Hellblock
version: '${project_version}'
api-version: 1.17
description: Skyblock in the nether!
website: https://github.com/Swiftlicious01
authors: [ Swiftlicious ]
folia-supported: true
load: STARTUP
softdepend:
- WorldEdit
- FastAsyncWorldEdit
- WorldGuard
- Multiverse-Core
- PlaceholderAPI
- PlayerPoints
- Vault
- SimplePets
- ChestShop
- QuickShop
- TradeShop
- MythicMobs
- Jobs
- mcMMO
- ShopGUIPlus
- StackMob
- WildStacker
- AdvancedEnchantments
- SlimeWorldPlugin
- SlimeWorldManager

permissions:
  hellblock.user:
    description: Main permission
    default: true
  hellblock.coop:
    description: Coop permission
    default: true
  hellblock.admin:
    description: Admin permission
    default: op
  hellblock.bypass.interact:
    description: Able to interact with any hellblock island regardless of being part of their party
    default: op
  hellblock.bypass.lock:
    description: Bypass locked hellblock islands whether or not they are locked
    default: op
  hellblock.updates:
    description: Get latest update messages
    default: op